package com.playpick.domain;

public enum FulfillmentStatus {
	PENDING_SUBMISSION,
	SUBMITTED,
	PRODUCTION_CONFIRMED,
	PRODUCTION_STARTED,
	PRODUCTION_COMPLETED,
	SHIPPING_DEPARTED,
	SHIPPING_DELIVERED,
	SIMULATED,
	FAILED,
	CANCELLED
}
