spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/${MYSQL_DATABASE:private_edition}?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${MYSQL_USERNAME:${SPRING_DATASOURCE_USERNAME:privateedition}}
    password: ${MYSQL_PASSWORD:${MYSQL_ROOT_PASSWORD:${SPRING_DATASOURCE_PASSWORD:privateedition}}}

  h2:
    console:
      enabled: false
